services:
  feedback:
    build: .
    ports:
      - "80:80"
    volumes:
      - feedback_data:/data
    restart: always

  notifier:
    build:
      context: ./notifier
    ports:
      - "5000:5000"
    restart: always


volumes:
  feedback_data:
